sudo: false
language: generic

cache:
  apt: true
  directories: /tmp/tools

matrix:
  include:
    - env: CC=gcc-5 CXX=g++-5
      addons:
        apt:
          packages: g++-5
          sources: ubuntu-toolchain-r-test
    - env: CC=clang-3.8 CXX=clang++-3.8
      addons:
        apt:
          packages: clang-3.8
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise']
    - env: CC=clang-3.7 CXX=clang++-3.7
      addons:
        apt:
          packages: clang-3.7
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
    - env: CC=clang-3.6 CXX=clang++-3.6
      addons:
        apt:
          packages: clang-3.6
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']

before_install:
  - export PATH="$HOME/bin:$PATH"
  - mkdir -p ~/bin /tmp/tools
  - wget --no-check-certificate --no-clobber -O /tmp/tools/cmake https://cmake.org/files/v3.4/cmake-3.4.3-rc3-Linux-x86_64.sh || true
  - chmod -R +x /tmp/tools

install: /tmp/tools/cmake --prefix="$HOME" --exclude-subdir

before_script:
  - mkdir build
  - cd build

script:
  - cmake -G"Unix Makefiles" ..
  - make
